### PR TITLE
fix: add RSuperellipse methods for Flutter 3.32 compat

### PR DESCRIPTION
**Pull request by jpohhhh**
## Description

Alchemist fails to build with Flutter 3.32. Error is in footer. Two new methods on Canvas for superellipse shapes are implemented to fix the error.

Tested by using this in my pubspec.yaml and confirming tests pass:
```
  alchemist:
    git:
      url: https://github.com/telosnex/alchemist
      ref: main
```

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Error
```
  Failed to load "/Users/jpo/dev/telosnex/test/mcp/tools/filesystem/read_multiple_files_golden_test.dart":
  Compilation failed for testPath=/Users/jpo/dev/telosnex/test/mcp/tools/filesystem/read_multiple_files_golden_test.dart: ../../.pub-cache/hosted/pub.dev/alchemist-0.11.0/lib/src/blocked_text_image.dart:65:7: Error: The non-abstract class 'BlockedTextCanvasAdapter' is missing implementations for these members:
   - Canvas.clipRSuperellipse
   - Canvas.drawRSuperellipse
  Try to either
   - provide an implementation,
   - inherit an implementation from a superclass or mixin,
   - mark the class as abstract, or
   - provide a 'noSuchMethod' implementation.
  
  class BlockedTextCanvasAdapter implements Canvas {
        ^^^^^^^^^^^^^^^^^^^^^^^^
  org-dartlang-sdk:///flutter/lib/ui/painting.dart:5910:8: Context: 'Canvas.clipRSuperellipse' is defined here.
    void clipRSuperellipse(RSuperellipse rsuperellipse, {bool doAntiAlias = true});
         ^^^^^^^^^^^^^^^^^
  org-dartlang-sdk:///flutter/lib/ui/painting.dart:6040:8: Context: 'Canvas.drawRSuperellipse' is defined here.
    void drawRSuperellipse(RSuperellipse rsuperellipse, Paint paint);
         ^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by btrautmann** [comment]
@jpohhhh thanks for the PR. I'm not sure why our compatibility checks did not catch this on the beta channel. It [passed 2 days ago on beta](https://github.com/Betterment/alchemist/actions/runs/15125795264/job/42517472873), but now failing for stable. 🤔

**Comment by btrautmann** [comment]
> @jpohhhh thanks for the PR. I'm not sure why our compatibility checks did not catch this on the beta channel. It [passed 2 days ago on beta](https://github.com/Betterment/alchemist/actions/runs/15125795264/job/42517472873), but now failing for stable. 🤔

OK I now see why this is the case. I forgot that I stood up the `beta` channel intentionally to fix this issue (that was done in https://github.com/Betterment/alchemist/commit/faceb493b9f41ae3e372c55a905d56de054181c0). The idea was to merge `beta` into stable once `stable` was released with these changes so we could continue to support older versions and not bump the min version constraint. I think it makes sense now to bump the min constraint. I will look into doing that.

**Comment by btrautmann** [comment]
Changes in this PR will be handled in https://github.com/Betterment/alchemist/pull/153.
